/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hrms;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import hrms.HRMS.search;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.plaf.basic.BasicScrollBarUI;
import javax.swing.table.JTableHeader;

/**
 *
 * @author AYSHA AQUINO
 */

public class Archive extends javax.swing.JPanel {
    
    public static String selectedProf;
    public Archive() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        archTbl = new javax.swing.JTable();
        Search = new javax.swing.JTextField();
        upButt = new javax.swing.JButton();

        jScrollPane1.getHorizontalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(255,51,0);
            }
        });

        jScrollPane1.getVerticalScrollBar().setUI(new BasicScrollBarUI() {
            @Override
            protected void configureScrollBarColors() {
                this.thumbColor = new Color(255,51,0);
            }
        });
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));

        TableCellRenderer baseRenderer = archTbl.getTableHeader().getDefaultRenderer();
        archTbl.getTableHeader().setDefaultRenderer(new TableHeaderRenderer(baseRenderer));

        archTbl.setDefaultRenderer(Object.class, new TableCellRenderer(){
            private DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = DEFAULT_RENDERER.getTableCellRendererComponent (table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    if (row%2 == 0) {
                        c.setBackground(new Color (255, 255, 255));
                        c.setForeground(new Color(0,0,0));
                    }
                    else {
                        c.setBackground(new Color (255, 102, 0));
                        c.setForeground(new Color(255,255,255));
                    }
                }
                else{
                    archTbl.setSelectionBackground(new java.awt.Color(0,51,204));
                    archTbl.setSelectionForeground(new java.awt.Color(255,255,255));
                }
                return c;
            }
        });

        JTableHeader header = archTbl.getTableHeader();
        header.setBackground(new Color(255,51,0));
        header.setForeground(new Color(255,255,255));
        archTbl.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        archTbl.setForeground(new java.awt.Color(255, 255, 255));
        archTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAME", "GENDER", "PROGRAM", "ABSENCES", "LATE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        archTbl.setGridColor(new java.awt.Color(255, 255, 255));
        archTbl.setShowHorizontalLines(false);
        jScrollPane1.setViewportView(archTbl);
        if (archTbl.getColumnModel().getColumnCount() > 0) {
            archTbl.getColumnModel().getColumn(0).setPreferredWidth(200);
            archTbl.getColumnModel().getColumn(1).setPreferredWidth(100);
            archTbl.getColumnModel().getColumn(1).setMaxWidth(100);
            archTbl.getColumnModel().getColumn(2).setPreferredWidth(100);
            archTbl.getColumnModel().getColumn(2).setMaxWidth(100);
            archTbl.getColumnModel().getColumn(3).setPreferredWidth(100);
            archTbl.getColumnModel().getColumn(3).setMaxWidth(100);
            archTbl.getColumnModel().getColumn(4).setPreferredWidth(100);
            archTbl.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        Search.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        Search.setText("SEARCH");
        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SearchFocusLost(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });

        upButt.setBackground(new java.awt.Color(0, 51, 204));
        upButt.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        upButt.setForeground(new java.awt.Color(255, 255, 255));
        upButt.setText("ADD TO ARCHIVE");
        upButt.setFocusPainted(false);
        upButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Search)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(upButt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addComponent(upButt)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusGained
        Search.setText(null);
    }//GEN-LAST:event_SearchFocusGained

    private void SearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SearchFocusLost
        Search.setText("SEARCH");
    }//GEN-LAST:event_SearchFocusLost

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        search s = new search();
        
        String query = Search.getText().toLowerCase();
        s.searcher (archTbl, archTbl.getModel(), Search);
    }//GEN-LAST:event_SearchKeyReleased

    private void upButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtActionPerformed
        AddArchive aa = new AddArchive(new javax.swing.JFrame(), true);
        aa.setVisible(true);
    }//GEN-LAST:event_upButtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Search;
    public static javax.swing.JTable archTbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton upButt;
    // End of variables declaration//GEN-END:variables
}
