/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package     hrms;

import static hrms.HRMS.getConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;
import static hrms.HRMS.TimeClass;
import static hrms.HRMS.FirstOpen;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author AYSHA AQUINO
 */
public class MainFrame extends javax.swing.JFrame {
    
    String active = "";
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPan = new javax.swing.JPanel();
        abc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TimeClass a = new TimeClass();
        dispTime = new javax.swing.JLabel();
        addEmp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        upEmp = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        archive = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        signOut = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CEE HR System");
        setMinimumSize(new java.awt.Dimension(750, 500));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPan.setBackground(new java.awt.Color(255, 51, 0));
        mainPan.setPreferredSize(new java.awt.Dimension(0, 0));
        mainPan.setBorder (new EmptyBorder (3,3,3,3));

        abc.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout mainPanLayout = new javax.swing.GroupLayout(mainPan);
        mainPan.setLayout(mainPanLayout);
        mainPanLayout.setHorizontalGroup(
            mainPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(abc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        mainPanLayout.setVerticalGroup(
            mainPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(abc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HUMAN RESOURCE MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COLLEGE OF ENGINEEERING EDUCATION");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("UNIVERSITY OF MINDANAO");

        dispTime.setFont(new java.awt.Font("Corbel", 0, 14)); // NOI18N
        dispTime.setForeground(new java.awt.Color(255, 255, 255));
        dispTime.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        dispTime.setText("MMM DD, YYYY - h : mm : ss");
        Timer dyn = new Timer(100, new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e ) {
                dispTime.setText(a.currentTime());
            }
        });

        dyn.start();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dispTime, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dispTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        addEmp.setBackground(new java.awt.Color(255, 51, 0));
        addEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmpMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Employee");

        javax.swing.GroupLayout addEmpLayout = new javax.swing.GroupLayout(addEmp);
        addEmp.setLayout(addEmpLayout);
        addEmpLayout.setHorizontalGroup(
            addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        addEmpLayout.setVerticalGroup(
            addEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        home.setBackground(new java.awt.Color(255, 51, 0));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Home");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        upEmp.setBackground(new java.awt.Color(255, 51, 0));
        upEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                upEmpMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update Details");

        javax.swing.GroupLayout upEmpLayout = new javax.swing.GroupLayout(upEmp);
        upEmp.setLayout(upEmpLayout);
        upEmpLayout.setHorizontalGroup(
            upEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        upEmpLayout.setVerticalGroup(
            upEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upEmpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        archive.setBackground(new java.awt.Color(255, 51, 0));
        archive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                archiveMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Archive");

        javax.swing.GroupLayout archiveLayout = new javax.swing.GroupLayout(archive);
        archive.setLayout(archiveLayout);
        archiveLayout.setHorizontalGroup(
            archiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        archiveLayout.setVerticalGroup(
            archiveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archiveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        settings.setBackground(new java.awt.Color(255, 51, 0));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                settingsMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Settings");

        javax.swing.GroupLayout settingsLayout = new javax.swing.GroupLayout(settings);
        settings.setLayout(settingsLayout);
        settingsLayout.setHorizontalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        settingsLayout.setVerticalGroup(
            settingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(settingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        signOut.setBackground(new java.awt.Color(255, 51, 0));
        signOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                signOutMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Sign Out");

        javax.swing.GroupLayout signOutLayout = new javax.swing.GroupLayout(signOut);
        signOut.setLayout(signOutLayout);
        signOutLayout.setHorizontalGroup(
            signOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        signOutLayout.setVerticalGroup(
            signOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(archive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(settings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(addEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(upEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(archive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                        .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(mainPan, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(916, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmpMouseClicked

        AddPanel aPanel = new AddPanel();
        active = "add";
        addEmp.setBackground(new Color (0,51,204));
        home.setBackground(new Color (255,51,0));
        archive.setBackground(new Color (255,51,0));
        settings.setBackground(new Color (255,51,0));
        upEmp.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(aPanel, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_addEmpMouseClicked

    private void settingsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMousePressed
        Settings set = new Settings();
        active = "set";
        settings.setBackground(new Color (0,51,204));
        addEmp.setBackground(new Color (255,51,0));
        archive.setBackground(new Color (255,51,0));
        home.setBackground(new Color (255,51,0));
        upEmp.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(set, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_settingsMousePressed

    private void homeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMousePressed
        Home hom = new Home();
        active = "home";
        home.setBackground(new Color (0,51,204));
        addEmp.setBackground(new Color (255,51,0));
        archive.setBackground(new Color (255,51,0));
        settings.setBackground(new Color (255,51,0));
        upEmp.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(hom, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
            
            PreparedStatement ps = getConnection().prepareStatement("select * from employees");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) hom.homeTable.getModel();
            tm.setRowCount(0);
                
            while(rs.next()) {
                String name = rs.getString("lastname")+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                String program = null;
                if (rs.getInt("program") == 0)
                    program = "BSChE";
                else if (rs.getInt("program") == 1)
                    program = "BSCE";    
                else if (rs.getInt("program") == 2)
                    program = "BSCpE";        
                else if (rs.getInt("program") == 3)
                    program = "BSEE";
                else if (rs.getInt("program") == 4)
                    program = "BSECE";
                else if (rs.getInt("program") == 5)
                    program = "BSME";
                
                Object o [] = {rs.getInt("id"), name,
                    program, rs.getInt("absent"), rs.getInt("late")};
                tm.addRow(o);
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_homeMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Home hom = new Home();
        TimeClass tc = new TimeClass();
        FirstOpen op = new FirstOpen();
        
        active = "home";
        home.setBackground(new Color (0,51,204));
        addEmp.setBackground(new Color (255,51,0));
        archive.setBackground(new Color (255,51,0));
        settings.setBackground(new Color (255,51,0));
        upEmp.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        Date date = new Date(System.currentTimeMillis());
        
        if(!tc.isFirstDayofMonth(date)) {
            op.setOpen("0");
        }
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(hom, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
            PreparedStatement ps = getConnection().prepareStatement("select * from employees");
            PreparedStatement up = getConnection().prepareStatement("UPDATE employees SET absent=? , late=?");
            up.setInt(1, 0);
            up.setInt(2, 0);
            
            if(tc.isFirstDayofMonth(date) && op.isFirstOpen()) {
                up.executeUpdate();
                op.setOpen("1");
            }
            
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) hom.homeTable.getModel();
            tm.setRowCount(0);
                
            while(rs.next()) {
                String name = rs.getString("lastname")+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                String program = null;

                if (rs.getInt("program") == 0)
                    program = "BSChE";
                else if (rs.getInt("program") == 1)
                    program = "BSCE";    
                else if (rs.getInt("program") == 2)
                    program = "BSCpE";        
                else if (rs.getInt("program") == 3)
                    program = "BSEE";
                else if (rs.getInt("program") == 4)
                    program = "BSECE";
                else if (rs.getInt("program") == 5)
                    program = "BSME";
                
                Object o [] = {rs.getInt("id"), name,
                    program, rs.getInt("absent"), rs.getInt("late")};
                tm.addRow(o);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void signOutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signOutMousePressed
        JLabel mess = new JLabel("Are you sure you want to exit?");
        Object[] opt = {"Yes", "No"};
        
        int n = JOptionPane.showOptionDialog(new JFrame(), mess, "",
                JOptionPane.YES_NO_CANCEL_OPTION, 
                JOptionPane.QUESTION_MESSAGE, null, opt, opt[1]);
        
        if (n==0) {
            try {
                getConnection().close();
            }
            catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            System.exit(0);
        }
        
        if (n==1) {
            
        }
        
    }//GEN-LAST:event_signOutMousePressed

    private void upEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upEmpMousePressed
        Update upd = new Update();
        active = "update";
        upEmp.setBackground(new Color (0,51,204));
        addEmp.setBackground(new Color (255,51,0));
        archive.setBackground(new Color (255,51,0));
        settings.setBackground(new Color (255,51,0));
        home.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(upd, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
            PreparedStatement ps = getConnection().prepareStatement("select * from employees");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) upd.upTable.getModel();
            tm.setRowCount(0);
                
            while(rs.next()) {
                String name = rs.getString("lastname")+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                String program = null;
                if (rs.getInt("program") == 0)
                    program = "BSChE";
                else if (rs.getInt("program") == 1)
                    program = "BSCE";    
                else if (rs.getInt("program") == 2)
                    program = "BSCpE";        
                else if (rs.getInt("program") == 3)
                    program = "BSEE";
                else if (rs.getInt("program") == 4)
                    program = "BSECE";
                else if (rs.getInt("program") == 5)
                    program = "BSME";
                
                Object o [] = {rs.getInt("id"), name,
                    rs.getString("gender"), program};
                tm.addRow(o);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_upEmpMousePressed

    private void archiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archiveMousePressed
        Archive arc = new Archive();
        active = "archive";
        archive.setBackground(new Color (0,51,204));
        addEmp.setBackground(new Color (255,51,0));
        home.setBackground(new Color (255,51,0));
        settings.setBackground(new Color (255,51,0));
        upEmp.setBackground(new Color (255,51,0));
        signOut.setBackground(new Color (255,51,0));
        
        try {
            abc.removeAll();
            abc.repaint();
            abc.revalidate();
            abc.add(arc, BorderLayout.CENTER);
            abc.repaint();
            abc.revalidate();
            
            PreparedStatement ps = getConnection().prepareStatement("select * from archive");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tm = (DefaultTableModel) arc.archTbl.getModel();
            tm.setRowCount(0);
                
            while(rs.next()) {
                String name = rs.getString("lastname")+", "+rs.getString("firstname")+" "+rs.getString("middlename");
                String program = null;
                if (rs.getInt("program") == 0)
                    program = "BSChE";
                else if (rs.getInt("program") == 1)
                    program = "BSCE";    
                else if (rs.getInt("program") == 2)
                    program = "BSCpE";        
                else if (rs.getInt("program") == 3)
                    program = "BSEE";
                else if (rs.getInt("program") == 4)
                    program = "BSECE";
                else if (rs.getInt("program") == 5)
                    program = "BSME";
                
                Object o [] = {name, rs.getString("gender"),
                    program, rs.getInt("tot_abs"), rs.getInt("tot_late")};
                tm.addRow(o);
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_archiveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel abc;
    private javax.swing.JPanel addEmp;
    private javax.swing.JPanel archive;
    private javax.swing.JLabel dispTime;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainPan;
    private javax.swing.JPanel settings;
    private javax.swing.JPanel signOut;
    private javax.swing.JPanel upEmp;
    // End of variables declaration//GEN-END:variables
}
